import Head from "next/head";
import Card from "../components/Card";

import subscriptions from '../data/subscriptions.json'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css"
        ></link>
      </Head>

      <main className="main">
        {subscriptions.map((subcription) => (
          <Card key={subscriptions.title} {...subcription} />
        ))}
      </main>
      <style jsx>{`
        .main {
          height: 100%;
          display: grid;
          gap: 20px;
          place-content: center;
        }
      `}</style>
    </>
  );
}
